import json
from datetime import UTC, datetime
from pathlib import Path

import pytest

from autodoc_harness.config import Config
from autodoc_harness.models import ComponentMap, ComponentNotes, ComponentRef, TraversalStats
from autodoc_harness.output_writer import dedupe_slugs, slugify, write_docs
from autodoc_harness.stages.synthesizer import SynthesizedDocs


def test_slugify_normalizes_messy_ids() -> None:
    assert slugify("Auth Service!!") == "auth-service"
    assert slugify("already-kebab") == "already-kebab"
    assert slugify("___") == "component"
    assert slugify("A__B") == "a-b"


def test_dedupe_slugs_appends_suffix_on_collision() -> None:
    result = dedupe_slugs(["Auth Service", "auth-service", "AUTH SERVICE"])
    assert result == {
        "Auth Service": "auth-service",
        "auth-service": "auth-service-2",
        "AUTH SERVICE": "auth-service-3",
    }


@pytest.fixture
def config(tmp_path: Path) -> Config:
    (tmp_path / "alpha.py").write_text("def alpha(): pass\n")
    return Config.model_validate(
        {
            "target_repo": str(tmp_path),
            "entry_points": ["alpha.py"],
            "model": {"name": "anthropic/claude-sonnet-4-5", "api_key_env": "ANTHROPIC_API_KEY"},
        }
    )


@pytest.fixture
def component_map(config: Config) -> ComponentMap:
    return ComponentMap(
        target_repo=str(config.target_repo),
        entry_points=["alpha.py"],
        components=[
            ComponentRef(
                component_id="Alpha Component",
                name="Alpha",
                summary="Does alpha things.",
                seed_paths=["alpha.py"],
                related_component_ids=[],
                role="core",
            )
        ],
        unresolved_notes=[],
        generated_at=datetime.now(UTC),
        model="anthropic/claude-sonnet-4-5",
        stats=TraversalStats(tool_calls=1, tokens_in=1, tokens_out=1, cost_usd=0.0, duration_s=0.1),
    )


@pytest.fixture
def component_notes() -> list[ComponentNotes]:
    return [
        ComponentNotes(
            component_id="Alpha Component",
            name="Alpha",
            status="ok",
            summary="alpha summary",
            files_visited=["alpha.py"],
            stats=TraversalStats(
                tool_calls=1, tokens_in=1, tokens_out=1, cost_usd=0.0, duration_s=0.1
            ),
        )
    ]


@pytest.fixture
def docs() -> SynthesizedDocs:
    return SynthesizedDocs(
        architecture_md="# Architecture body",
        api_reference_md="# API reference body",
        module_docs={"Alpha Component": "# Alpha module body"},
    )


def test_write_docs_creates_expected_layout(
    config: Config,
    component_map: ComponentMap,
    component_notes: list[ComponentNotes],
    docs: SynthesizedDocs,
) -> None:
    docs_dir = write_docs(component_map, component_notes, docs, config)

    assert docs_dir == config.target_repo / "docs"
    assert (docs_dir / "architecture.md").is_file()
    assert (docs_dir / "api-reference.md").is_file()
    assert (docs_dir / "modules" / "alpha-component.md").is_file()
    assert (docs_dir / ".autodoc-harness" / "component-map.json").is_file()
    assert (docs_dir / ".autodoc-harness" / "component-notes" / "alpha-component.json").is_file()
    assert (docs_dir / ".autodoc-harness" / "run-manifest.json").is_file()


def test_written_docs_include_generated_header(
    config: Config,
    component_map: ComponentMap,
    component_notes: list[ComponentNotes],
    docs: SynthesizedDocs,
) -> None:
    docs_dir = write_docs(component_map, component_notes, docs, config)
    content = (docs_dir / "architecture.md").read_text()
    assert "GENERATED by autodoc-harness" in content
    assert "anthropic/claude-sonnet-4-5" in content
    assert "# Architecture body" in content


def test_run_manifest_hashes_visited_files(
    config: Config,
    component_map: ComponentMap,
    component_notes: list[ComponentNotes],
    docs: SynthesizedDocs,
) -> None:
    docs_dir = write_docs(component_map, component_notes, docs, config)
    manifest = json.loads((docs_dir / ".autodoc-harness" / "run-manifest.json").read_text())
    assert "alpha.py" in manifest["files"]
    assert len(manifest["files"]["alpha.py"]) == 64  # sha256 hex digest length


def test_rerun_clears_stale_module_docs(
    config: Config,
    component_map: ComponentMap,
    component_notes: list[ComponentNotes],
    docs: SynthesizedDocs,
) -> None:
    docs_dir = write_docs(component_map, component_notes, docs, config)
    assert (docs_dir / "modules" / "alpha-component.md").is_file()

    # Simulate a second run where the "alpha" component no longer exists.
    empty_map = component_map.model_copy(update={"components": []})
    empty_docs = SynthesizedDocs(
        architecture_md="# New architecture", api_reference_md="# New api", module_docs={}
    )
    write_docs(empty_map, [], empty_docs, config)

    assert not (docs_dir / "modules" / "alpha-component.md").exists()
    assert not (docs_dir / ".autodoc-harness" / "component-notes" / "alpha-component.json").exists()
    assert "New architecture" in (docs_dir / "architecture.md").read_text()
