"""Output writer: writes the Synthesizer's markdown docs, plus a machine-readable
audit trail, into the target repo's `docs/` directory.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import UTC, datetime
from pathlib import Path

from autodoc_harness.config import Config
from autodoc_harness.models import ComponentMap, ComponentNotes, ReviewReport
from autodoc_harness.stages.synthesizer import SynthesizedDocs

GENERATED_HEADER_TEMPLATE = """\
<!--
GENERATED by autodoc-harness on {timestamp} using model "{model}".
Do not hand-edit - regenerate via `autodoc-harness generate` instead, or your
changes will be silently overwritten on the next run.
-->

"""

_SLUG_INVALID_CHARS_RE = re.compile(r"[^a-z0-9-]+")
_DASH_COLLAPSE_RE = re.compile(r"-{2,}")


def slugify(component_id: str) -> str:
    """Normalize a model-produced `component_id` into a filesystem-safe slug.

    Nothing guarantees the model's `component_id` values are already
    lowercase/kebab-case - this is the harness's own safety net, applied
    regardless of what the model actually produced.
    """
    slug = _SLUG_INVALID_CHARS_RE.sub("-", component_id.lower())
    slug = _DASH_COLLAPSE_RE.sub("-", slug).strip("-")
    return slug or "component"


def dedupe_slugs(component_ids: list[str]) -> dict[str, str]:
    """Map each `component_id` to a unique slug, appending `-2`, `-3`, ... on
    collision - nothing guarantees the model's component_ids produce distinct
    slugs once normalized."""
    seen: dict[str, int] = {}
    result: dict[str, str] = {}
    for component_id in component_ids:
        base = slugify(component_id)
        count = seen.get(base, 0) + 1
        seen[base] = count
        result[component_id] = base if count == 1 else f"{base}-{count}"
    return result


def _with_header(content: str, *, model: str, timestamp: str) -> str:
    header = GENERATED_HEADER_TEMPLATE.format(timestamp=timestamp, model=model)
    return header + content.rstrip() + "\n"


def _build_run_manifest(component_notes: list[ComponentNotes], config: Config) -> dict[str, object]:
    """Every file this run is known to have read, plus a content hash.

    A cheap forward-compatibility hook: a future incremental mode could diff this
    against a prior run's manifest to skip unchanged components, without building
    that diffing logic now.
    """
    visited: set[str] = set()
    for notes in component_notes:
        visited.update(notes.files_visited)

    files: dict[str, str] = {}
    for rel_path in sorted(visited):
        abs_path = config.target_repo / rel_path
        if abs_path.is_file():
            files[rel_path] = hashlib.sha256(abs_path.read_bytes()).hexdigest()

    return {"generated_at": datetime.now(UTC).isoformat(), "files": files}


def write_docs(
    component_map: ComponentMap,
    component_notes: list[ComponentNotes],
    docs: SynthesizedDocs,
    config: Config,
    *,
    review_report: ReviewReport | None = None,
) -> Path:
    """Write the full doc set into `<target_repo>/<output.dir>`.

    Clears and rewrites the files this harness owns on every call, consistent with
    the MVP's one-shot, `output.overwrite: true`-only semantics (see `config.py` -
    `overwrite: false` is rejected at config-load time, before we ever get here).

    Returns the docs directory path.
    """
    docs_dir = config.target_repo / config.output.dir
    modules_dir = docs_dir / "modules"
    metadata_dir = docs_dir / ".autodoc-harness"
    notes_dir = metadata_dir / "component-notes"
    modules_dir.mkdir(parents=True, exist_ok=True)
    notes_dir.mkdir(parents=True, exist_ok=True)

    # Clear stale per-component files from a previous run before writing the
    # current set - components can be renamed/removed between runs.
    for stale in (*modules_dir.glob("*.md"), *notes_dir.glob("*.json")):
        stale.unlink()

    timestamp = datetime.now(UTC).isoformat()
    model = component_map.model

    (docs_dir / "architecture.md").write_text(
        _with_header(docs.architecture_md, model=model, timestamp=timestamp)
    )
    (docs_dir / "api-reference.md").write_text(
        _with_header(docs.api_reference_md, model=model, timestamp=timestamp)
    )

    slugs = dedupe_slugs([n.component_id for n in component_notes])

    for component_id, content in docs.module_docs.items():
        slug = slugs.get(component_id, slugify(component_id))
        (modules_dir / f"{slug}.md").write_text(
            _with_header(content, model=model, timestamp=timestamp)
        )

    for notes in component_notes:
        slug = slugs.get(notes.component_id, slugify(notes.component_id))
        (notes_dir / f"{slug}.json").write_text(notes.model_dump_json(indent=2))

    (metadata_dir / "component-map.json").write_text(component_map.model_dump_json(indent=2))
    manifest = _build_run_manifest(component_notes, config)
    (metadata_dir / "run-manifest.json").write_text(json.dumps(manifest, indent=2))

    if review_report is not None:
        (metadata_dir / "review-report.json").write_text(review_report.model_dump_json(indent=2))
    else:
        stale_report = metadata_dir / "review-report.json"
        stale_report.unlink(missing_ok=True)

    return docs_dir
